<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BlazeAccountingSummary extends Model
{
    protected $table = 'blaze_accounting_summary';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'date',
        'shop',
        'company',
        'queue_type',
        'adult_retail_value_of_sales',
        'medical_retail_value_of_sales',
        'non_cannabis_retail_value_of_sales',
        'retail_value_of_sales',
        'pre_al_excise_tax',
        'pre_nal_excise_tax',
        'pre_city_tax',
        'pre_county_tax',
        'pre_state_tax',
        'pre_federal_tax',
        'adult_gross_sales',
        'medical_gross_sales',
        'non_cannabis_gross_sales',
        'gross_sales',
        'delivery_fee',
        'ach_fee',
        'blazepay_fee',
        'aeropay_fee',
        'blazepay_ach_fee',
        'cashless_atm_fee',
        'cash_fee',
        'credit_debit_fee',
        'stronghold_fee',
        'pre_tax_discount',
        'adult_net_sales',
        'adult_net_sales_wo_fees',
        'medical_net_sales',
        'medical_net_sales_wo_fees',
        'non_cannabis_net_sales',
        'non_cannabis_net_sales_wo_fees',
        'net_sales',
        'net_sales_wo_fees',
        'post_al_excise_tax',
        'post_nal_excise_tax',
        'post_city_tax',
        'post_county_tax',
        'post_state_tax',
        'post_federal_tax',
        'delivery_fee_excise_tax',
        'city_delivery_fee_tax',
        'county_delivery_fee_tax',
        'state_delivery_fee_tax',
        'federal_delivery_fee_tax',
        'adult_total_tax',
        'medical_total_tax',
        'non_cannabis_total_tax',
        'total_tax',
        'after_tax_discount',
        'rounding',
        'adjustments',
        'adult_total_due',
        'medical_total_due',
        'non_cannabis_total_due',
        'total_due',
        'tips',
        'blazepay_tips',
        'aeropay_tips',
        'blazepay_ach_tips',
        'number_of_transactions',
        'count_of_completed_sales',
        'count_of_refunds',
        'new_members',
        'returning_members',
        'adult_cogs',
        'medical_cogs',
        'non_cannabis_cogs',
        'ach_tendered',
        'blazepay_tendered',
        'aeropay_tendered',
        'blazepay_ach_tendered',
        'cashless_atm_tendered',
        'cash_tendered',
        'check_tendered',
        'credit_debit_tendered',
        'gift_card_tendered',
        'birchmount_tendered',
        'store_credit_tendered',
        'stronghold_tendered',
        'payment_tendered',
        'ach_change_due',
        'blazepay_change_due',
        'aeropay_change_due',
        'blazepay_ach_change_due',
        'cashless_atm_change_due',
        'cash_change_due',
        'check_change_due',
        'credit_debit_change_due',
        'gift_card_change_due',
        'store_credit_change_due',
        'stronghold_change_due',
        'change_due',
        'items_sold',
        'items_refunded',
        'refund_total_due',
        'surcharge_fee_tax',
        'blazepay_cashback',
        'aeropay_cashback',
        'blazepay_ach_cashback',
        'cashless_atm_cashback',
        'untaxed_fee',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'date' => 'date',
            'number_of_transactions' => 'integer',
            'count_of_completed_sales' => 'integer',
            'count_of_refunds' => 'integer',
            'new_members' => 'integer',
            'returning_members' => 'integer',
            'items_sold' => 'integer',
            'items_refunded' => 'integer',
        ];
    }
}
